[project]
name = "ridge-regression"
version = "0.1.0"
description = "Framework for a ridge regression model."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
]
